import _ from 'lodash';
import './js/initializers/av.js';
import './js/initializers/init-swiper.js';
import './js/admin/event-hub.js';
import './js/player/player.js';
import './js/player/process.js';
import './js/player/songlist.js';
import './js/player/song-title.js';
import './css/reset.css';
import './css/style.css';
